version: '3'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Asia/Seoul
      - N8N_USER_FOLDER=/home/node/.n8n
    volumes:
      - ./n8n-workflows:/home/node/.n8n
    user: "1000:1000"
    restart: unless-stopped
